from __future__ import annotations
from datetime import datetime, timezone
from typing import Optional
from sqlmodel import Field, SQLModel


class CampaignBrief(SQLModel, table=True):
    """
    A campaign brief generated by Leon and handed off to SAPP's Campaign Room.
    
    Flow:
      Leon creates product -> auto-generates brief -> brief stored here
      SAPP Campaign Room polls GET /store/campaign-briefs?status=pending
      SAPP picks up brief -> creates campaign -> marks brief as 'accepted'
      Hunter tracks campaign performance back from SAPP
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    product_id: Optional[int] = Field(default=None, foreign_key="createdproduct.id", index=True)
    product_name: str
    status: str = Field(default="pending", index=True)  # pending | accepted | in_progress | launched | cancelled
    
    # Campaign content
    campaign_title: str
    product_description: str
    target_audience: Optional[str] = None
    key_message: Optional[str] = None
    urgency_note: Optional[str] = None  # e.g. "Juneteenth in 37 days"
    
    # Platform priorities
    platforms: Optional[str] = None  # JSON list: ["tiktok", "instagram", "youtube"]
    hashtags: Optional[str] = None   # JSON list
    
    # Creative direction for SAPP
    video_concept: Optional[str] = None
    social_caption: Optional[str] = None
    image_prompt: Optional[str] = None  # for SAPP Video Bay / Image generation
    
    # Pricing & commerce
    price: Optional[float] = None
    platform: Optional[str] = None  # etsy, gumroad, shopify
    product_url: Optional[str] = None
    
    # Deadlines
    launch_target_date: Optional[datetime] = None
    campaign_end_date: Optional[datetime] = None
    
    # Tracking
    sapp_campaign_id: Optional[str] = None  # ID returned from SAPP once accepted
    notes: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: Optional[datetime] = None
