"""
Operations dashboard endpoints.

GET /operations/summary   — high-level system health snapshot
GET /operations/pipeline  — opportunity pipeline breakdown by status/band
GET /operations/events    — recent audit events (optionally filtered by source)
"""

from typing import Optional

from fastapi import APIRouter, Depends
from sqlmodel import Session, func, select

from app.database.config import get_session
from app.models.event import OpportunityEvent
from app.models.income_source import IncomeSource, PriorityBand, SourceStatus
from app.models.action_packet import ActionPacket, ExecutionState, PacketStatus
from app.models.strategy import Strategy, StrategyStatus
from app.services import strategies as strategy_svc
from app.services import alerts as alert_svc
from app.services import budget as budget_svc
from app.services import execution as execution_svc

router = APIRouter(prefix="/operations", tags=["operations"])


@router.get("/summary")
def operations_summary(session: Session = Depends(get_session)):
    total_sources = session.exec(select(func.count(IncomeSource.id))).one()
    active_sources = session.exec(
        select(func.count(IncomeSource.id)).where(IncomeSource.status == SourceStatus.active)
    ).one()
    elite_count = session.exec(
        select(func.count(IncomeSource.id)).where(IncomeSource.priority_band == PriorityBand.elite)
    ).one()
    high_count = session.exec(
        select(func.count(IncomeSource.id)).where(IncomeSource.priority_band == PriorityBand.high)
    ).one()
    unack_alerts = len(alert_svc.get_active_alerts(session))
    ready_packets = session.exec(
        select(func.count(ActionPacket.id)).where(ActionPacket.status == PacketStatus.ready)
    ).one()
    active_executions = session.exec(
        select(func.count(ActionPacket.id)).where(
            ActionPacket.execution_state.in_([ExecutionState.active.value, ExecutionState.in_progress.value])
        )
    ).one()
    completed_executions = session.exec(
        select(func.count(ActionPacket.id)).where(ActionPacket.execution_state == ExecutionState.completed)
    ).one()
    failed_executions = session.exec(
        select(func.count(ActionPacket.id)).where(
            ActionPacket.execution_state.in_([ExecutionState.failed.value, ExecutionState.canceled.value])
        )
    ).one()
    underperforming_strategies = session.exec(
        select(func.count(Strategy.id)).where(Strategy.status == StrategyStatus.underperforming)
    ).one()
    strategy_quota = strategy_svc.check_quota(session)
    source_discovery_quota = strategy_svc.check_source_discovery_quota(session)
    open_budget = budget_svc.get_open_budget(session)

    all_quotas_met = strategy_quota["quota_met"] and source_discovery_quota["quota_met"]

    return {
        "total_opportunities": total_sources,
        "active_opportunities": active_sources,
        "elite_opportunities": elite_count,
        "high_opportunities": high_count,
        "unacknowledged_alerts": unack_alerts,
        "ready_packets": ready_packets,
        "execution": {
            "active": active_executions,
            "completed": completed_executions,
            "failed": failed_executions,
        },
        "underperforming_strategies": underperforming_strategies,
        "budget": (
            {
                "status": "open",
                "starting_bankroll": open_budget.starting_bankroll,
                "current_bankroll": budget_svc.recalc_current_bankroll(session, open_budget),
                "available_capital": budget_svc.recalc_remaining(session, open_budget),
                "committed_capital": budget_svc.recalc_committed_capital(session, open_budget),
                "realized_profit": budget_svc.recalc_realized_return(session, open_budget),
                "evaluation_end_date": open_budget.evaluation_end_date.isoformat(),
            }
            if open_budget
            else {"status": "no_active_bankroll"}
        ),
        "execution_provider": execution_svc.get_execution_provider_status(session),
        "weekly_quotas": {
            "all_met": all_quotas_met,
            "source_discovery": source_discovery_quota,
            "strategy_deployment": strategy_quota,
        },
    }


@router.get("/pipeline")
def pipeline_breakdown(session: Session = Depends(get_session)):
    """Count of opportunities by status and priority band."""
    # By status
    status_counts: dict[str, int] = {}
    for status in SourceStatus:
        count = session.exec(
            select(func.count(IncomeSource.id)).where(IncomeSource.status == status.value)
        ).one()
        if count:
            status_counts[status.value] = count

    # By band
    band_counts: dict[str, int] = {}
    for band in PriorityBand:
        count = session.exec(
            select(func.count(IncomeSource.id)).where(IncomeSource.priority_band == band.value)
        ).one()
        if count:
            band_counts[band.value] = count

    # Top elite/high sources
    top_sources = session.exec(
        select(IncomeSource)
        .where(IncomeSource.score != None)  # noqa: E711
        .order_by(IncomeSource.score.desc())
        .limit(10)
    ).all()

    return {
        "by_status": status_counts,
        "by_band": band_counts,
        "top_10": [
            {
                "source_id": s.source_id,
                "description": s.description,
                "score": s.score,
                "priority_band": s.priority_band,
                "status": s.status,
                "estimated_profit": s.estimated_profit,
            }
            for s in top_sources
        ],
    }


@router.post("/run-quotas")
def run_quotas_now(session: Session = Depends(get_session)):
    """
    Manually trigger the full weekly quota enforcement cycle:
    source discovery check, strategy auto-promote, stale strategy detection.
    Equivalent to the quota step of the daily pipeline, callable on demand.
    """
    from app.services.scheduler import _run_weekly_quota_checks
    return _run_weekly_quota_checks(session)


@router.get("/events")
def recent_events(source_id: Optional[str] = None, limit: int = 100, session: Session = Depends(get_session)):
    stmt = select(OpportunityEvent).order_by(OpportunityEvent.created_at.desc()).limit(limit)
    if source_id:
        stmt = (
            select(OpportunityEvent)
            .where(OpportunityEvent.source_id == source_id)
            .order_by(OpportunityEvent.created_at.desc())
            .limit(limit)
        )
    events = list(session.exec(stmt).all())
    return {"count": len(events), "events": events}


    @router.post("/run-decisions")
    def run_decisions_now(session: Session = Depends(get_session)):
        """Re-run decision engine on all scored sources using current thresholds.
            Updates execution_ready flags in-place. Call after deploying threshold changes."""
                from app.services.decision import run_decisions
                    return run_decisions(session)


                    @router.post("/run-pipeline")
                    def run_pipeline_now(session: Session = Depends(get_session)):
                        """Allocate budget + place trades for all execution_ready trading decisions."""
                            from app.models.decision import OpportunityDecision
                                from app.models.budget import BudgetAllocation
                                    from app.services.budget import auto_allocate_for_source
                                        from app.services.execution import auto_place_trade_for_source
                                            ready = session.exec(
                                                    select(OpportunityDecision).where(
                                                                OpportunityDecision.execution_ready == True,  # noqa: E712
                                                                            OpportunityDecision.execution_path == "trading",
                                                                                    )
                                                                                        ).all()
                                                                                            out: dict = {"eligible": len(ready), "allocated": 0, "allocation_skipped": 0,
                                                                                                             "trades_placed": 0, "errors": []}
                                                                                                                 for dec in ready:
                                                                                                                         has_alloc = session.exec(
                                                                                                                                     select(BudgetAllocation).where(BudgetAllocation.source_id == dec.source_id)
                                                                                                                                             ).first()
                                                                                                                                                     if not has_alloc:
                                                                                                                                                                 try:
                                                                                                                                                                                 r = auto_allocate_for_source(dec.source_id, session)
                                                                                                                                                                                                 if r and not r.get("skipped"):
                                                                                                                                                                                                                     out["allocated"] += 1
                                                                                                                                                                                                                                     else:
                                                                                                                                                                                                                                                         out["allocation_skipped"] += 1
                                                                                                                                                                                                                                                                     except Exception as exc:
                                                                                                                                                                                                                                                                                     out["errors"].append({"source_id": dec.source_id, "step": "allocate",
                                                                                                                                                                                                                                                                                                                           "error": str(exc)})
                                                                                                                                                                                                                                                                                                                                           continue
                                                                                                                                                                                                                                                                                                                                                   else:
                                                                                                                                                                                                                                                                                                                                                               out["allocation_skipped"] += 1
                                                                                                                                                                                                                                                                                                                                                                       try:
                                                                                                                                                                                                                                                                                                                                                                                   trade = auto_place_trade_for_source(dec.source_id, session)
                                                                                                                                                                                                                                                                                                                                                                                               if trade:
                                                                                                                                                                                                                                                                                                                                                                                                               out["trades_placed"] += 1
                                                                                                                                                                                                                                                                                                                                                                                                                       except Exception as exc:
                                                                                                                                                                                                                                                                                                                                                                                                                                   out["errors"].append({"source_id": dec.source_id, "step": "trade",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "error": str(exc)})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return OutcomeRequest

                                                                                                                                                                                                                                                                                                                                                                                                                                                                         @router.get("/diagnostics")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         def execution_diagnostics(session: Session = Depends(get_session)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             """Explain why committed_capital or funded_packets may be zero."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 from app.models.decision import OpportunityDecision
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     from app.models.budget import BudgetAllocation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         from app.services.decision import _thresholds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             import app.services.execution as execution_svc

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 t = _thresholds()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     all_d = session.exec(select(OpportunityDecision)).all()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         by_state: dict[str, int] = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             by_path: dict[str, int] = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 for d in all_d:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         by_state[d.action_state] = by_state.get(d.action_state, 0) + 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 by_path[d.execution_path] = by_path.get(d.execution_path, 0) + 1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     scored = session.exec(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             select(IncomeSource).where(IncomeSource.score.is_not(None))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ).all()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     trading = [s for s in scored if (s.category or "").lower() == "trading"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         t_ids = [s.source_id for s in trading]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             t_allocs = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if t_ids:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         t_allocs = session.exec(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     select(func.count(BudgetAllocation.id)).where(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     BudgetAllocation.source_id.in_(t_ids)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ).one()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             exec_ready = sum(1 for d in all_d if d.execution_ready)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 diag: list[str] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if exec_ready == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             meet_criteria = sum(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1 for s in trading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (s.score or 0) >= t["auto_execute_score"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 and (s.confidence or 0) >= t["auto_execute_confidence"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             and (s.estimated_profit or 0) <= t["auto_execute_max_capital"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             diag.append(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         f"No execution_ready decisions. {len(trading)} trading sources; "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     f"{meet_criteria} meet auto_execute criteria "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 f"(score>={t['auto_execute_score']}, conf>={t['auto_execute_confidence']}, "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             f"profit<={t['auto_execute_max_capital']}). "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         f"Run POST /operations/run-decisions to reprocess with current thresholds."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             diag.append(f"{exec_ready} execution_ready decisions found.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if t_allocs == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 diag.append(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "No budget allocations for trading sources. "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "Run POST /operations/run-pipeline to allocate and execute."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 broker = execution_svc.get_execution_provider_status(session)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if not broker.get("connected"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             diag.append(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         f"Execution provider not connected: {broker.get('error', 'unknown')}. "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Check ALPACA_API_KEY / ALPACA_SECRET_KEY."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if not diag:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         diag.append("Execution pipeline appears healthy.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "thresholds": t,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "decisions": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "total": len(all_d),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "execution_ready": exec_ready,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "by_action_state": by_state,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "by_execution_path": by_path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "blocked_by_approval": sum(1 for d in all_d if d.blocked_by == "approval"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "trading_sources": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "total": len(trading),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "with_allocations": t_allocs,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "without_allocations": len(trading) - t_allocs,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "broker": broker,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "diagnosis": diag,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "blocked_trading_sample": [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "source_id": d.source_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "action_state": d.action_state,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "blocked_by": d.blocked_by,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "score": d.score_at_decision,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "confidence": d.confidence_at_decision,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "capital_rec": d.capital_recommendation,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 for d in all_d
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if d.execution_path == "trading" and not d.execution_ready
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ][:15],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
